columnSuffix: mxdhqtxh
contentColumnType: text
fieldGroup: 432101b2-60c4-4648-85d0-ce89ccf2dad2 # Common
handle: headerTitle
instructions: ''
name: 'Header Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
