columnSuffix: egddygip
contentColumnType: text
fieldGroup: 432101b2-60c4-4648-85d0-ce89ccf2dad2 # Common
handle: subtitle
instructions: 'Enter a subtitle'
name: Subtitle
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
