dateModified: 1644519445
email:
  fromEmail: frankluisravlo@gmail.com
  fromName: 'Craft Test'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    001a8fca-6de6-4d7e-865e-e575aefcf5f4: NavBar # NavBar
    5a952317-2f39-4497-a59e-6b24ded4693d: 'Hero Image' # Hero Image
    5c65eb74-25bf-4ea1-b4a6-28e6d9a00b83: 'Boxes Categories' # Boxes Categories
    22b10151-540d-449f-b8e2-c6a4cc4887e9: 'Header Title' # Header Title
    82c6f946-5b9a-4f1e-a9e6-770a2c76bdd7: Boxes # Boxes
    0980bef2-0084-459a-96f3-affdaa222dca: 'Craft Test' # Craft Test
    432101b2-60c4-4648-85d0-ce89ccf2dad2: Common # Common
    b453e6c7-4dcb-4711-b217-62ddd3351526: Home # Home
    bf346d29-2efa-4e20-a368-5bc907d79d0a: Default # Default
    cc13e251-63bd-43e6-9a2a-623700a63e01: 'Craft Test' # Craft Test
    d309aa79-2abc-449b-8ce0-21f361bebfe7: Home # Home
    db1540ab-4b16-429c-95da-8f7bc67f41d5: 'Header Subtitle' # Header Subtitle
    e31b7f96-999f-4685-b515-0b2bff1c87b9: 'Box Subtitle' # Box Subtitle
    e93490a4-1acf-4c1d-b62d-eb7127e450e6: Assets # Assets
    ebbd4619-5032-4884-b341-d2788871984a: 'Category Field' # Category Field
plugins:
  navigation:
    edition: standard
    enabled: true
    licenseKey: WIQSDK7NYEC2C1CXI5C1HKR4
    schemaVersion: 1.0.21
system:
  edition: solo
  live: true
  name: 'Craft Test'
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
