defaultPlacement: end
enableVersioning: true
handle: boxes
name: Boxes
propagationMethod: all
siteSettings:
  cc13e251-63bd-43e6-9a2a-623700a63e01: # Craft Test
    enabledByDefault: true
    hasUrls: true
    template: boxes/_entry
    uriFormat: 'boxes/{slug}'
type: channel
